### ISSUE TITLE
Rulers are too bright and colorful

### ISSUE THREAD

**Issue by DanielPower** [sainnhe/sonokai-vscode#1]
In my opinion, the rulers are much too obnoxious, otherwise I really enjoy this theme. 
![Screen Shot 2020-04-27 at 6 55 08 AM](https://user-images.githubusercontent.com/12166320/80356473-163dca00-8854-11ea-8dec-0b9c432b3bae.png)

**Comment by sainnhe** [comment]
Fixed.

**Comment by DanielPower** [comment]
This looks great. Thanks so much!
