### ISSUE TITLE
New list focus colors in 1.57

### ISSUE THREAD

**Issue by adamcstephens** [sainnhe/sonokai-vscode#3]
https://code.visualstudio.com/updates/v1_57#_updated-quick-pick-suggest-widget-colors

The line with the arrow on it is the selection, but this is no longer different from the surrounding list lines.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/2071575/121587229-8da3ce00-ca02-11eb-9211-221de8415126.png">

Verified this is the same across all the Sonokai variations.

**Comment by sainnhe** [comment]
Sorry I don't have much time recently, I'll fix it later, but PR is welcome.
