### ISSUE TITLE
Theme proposal.

### ISSUE THREAD

**Issue by BarreiroLeo** [sainnhe/sonokai-vscode#5]
My favourite theme is Monokai Pro Filter Spectrum. Based in on it, I took these colors and here are the results.

```
// Theme base: Sonokai Espresso
"workbench.colorCustomizations": {
    "terminal.background": "#111111",
    "editor.background": "#222222",
    "sideBar.background": "#191919",
    "statusBar.background": "#191919",
    "titleBar.activeBackground": "#191919",
    "titleBar.inactiveBackground": "#191919",
    "activityBar.background": "#131313"
}
```
![monokai espresso](https://user-images.githubusercontent.com/48270301/129641010-f0163f15-29fc-4be8-815c-61735aca0a9c.png)
I need to test it in vim, but I don't have much time..

@sainnhe you work is awesome, thanks a lot!

**Comment by sainnhe** [comment]
As I said in readme, I'm not interested in porting all variants of monokai pro to sonokai.

So, sorry, you can install monokai pro in vscode or fork this repo instead.
